name: uj_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ikonok
  cupertino_icons: ^1.0.8

  # Adatbázis (SQLite)
  sqflite: ^2.3.0
  path: ^1.9.0
  
  # EZ KELL A CHROME TESZTHEZ:
  sqflite_common_ffi: ^2.3.1
  sqflite_common_ffi_web: ^0.4.0

  # Beszédvezérlés
  speech_to_text: ^6.6.1

  # Egyéb hasznos apróságok
  shared_preferences: ^2.2.0
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # IDE KERÜLT BE AZ ADATBÁZIS FÁJL:
flutter:  
assets:
    - assets/beekeeping.db